version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    volumes:
      - ./redisinsight:/db

  mongodb:
    image: mongo:latest
    container_name: db_tp
    ports:
      - 27018:27017
    volumes:
      - data:/data/db
      - ./mflix:/mflix
volumes:
  data:
      
